### ISSUE TITLE
Use steamdb.info to find App ID, Depot ID, Mainfest ID

### ISSUE THREAD

**Issue by Hexaae** [mmvanheusden/SteamDepotDownloaderGUI#113]
Would be nice adding an option to automatically find App ID, Depot ID, Manifest ID using steamdb.info, so that you can enter game name, and then select Manifest ID from a list, linking this tool to SteamDB.info.

E.g. I want to download Bioshock II Remastered...

1. enter "Biosho..." in the input gadget and it will automatically suggest Bioshock I, II and everything else with "biosho" string...
2. select Manifest ID (aka the old version you want) from a top-down cycle-gadget)

Simpler than having to manually go to steamdb.info to search for those 3 datas...

**Comment by Bluscream** [comment]
The problem is that steamdb does not allow usage of it's APIs or scraping, so we would have to use Steam's API directly like SteamDB does in the background.

**Comment by Hexaae** [comment]
It would be great!

**Comment by mmvanheusden** [comment]
I'm not completely confident I have the skills to make this, but I'll look into it

**Comment by mmvanheusden** [comment]
I have tried to make this in Python, but there really is no easy way to do this.

**Comment by mmvanheusden** [comment]
stale
