### ISSUE TITLE
[bug] not opening

### ISSUE THREAD

**Issue by sithydev** [mmvanheusden/SteamDepotDownloaderGUI#147]
its not opening when i open the .exe file.

**Comment by mmvanheusden** [comment]
Huh, that's weird. Just to verify, you are on Windows right?
and can you try to open another electron-based app, like VS Code or Atom, to verify it's a SteamDepotDownloaderGUI-specific issue.

**Comment by mmvanheusden** [comment]
Try this one: https://filetransfer.kpn.com/download/e6ae4f9f-fa7c-431f-a660-dc72004863cc#jhUIYieIx86BtdirrZDAN5c_TJjR2dzlT5OZAGVO0Mc
