### ISSUE TITLE
Needs instructions for installing on the Steam Deck

### ISSUE THREAD

**Issue by Deus-nsf** [mmvanheusden/SteamDepotDownloaderGUI#149]
Unfortunately the Steam Deck doesn't support the AUR (sad), so I tried all the manual things I could try to install .NET 6.0 (which is apparently required), even downloaded the Windows version of this app to use Proton to launch it, and download + install .NET 6.0 through Proton for the same prefix, but the download still fails even after reboot.

Not sure what you could do about that, maybe a flatpak could create the necessary dependencies automatically?

**Comment by mmvanheusden** [comment]
Hey. Is there maybe a Wine option? because you can install .NET sdk on there.

I will definitly look into creating a Steam Deck version. I don't have one myself sadly but I can try to make something out of it that will somehwat function. Probably a version where you can choose the path .NET is installed to. So you don't have to mess with system paths or something

**Comment by Deus-nsf** [comment]
Honestly with SteamOS supporting Flatpaks since last year, most simple would be to do a Flatpak version on the Flathub, that may even make getting additional dependencies automatic?

**Comment by mmvanheusden** [comment]
I'll look into that. Will probably be hard getting it on flathub tho as .NET obviously isn't open source (i think).
But maybe adding some way of downloading it automatically would be a good feature

**Comment by mmvanheusden** [comment]
Feature is on the way!
will also look into flatpak support

**Comment by mmvanheusden** [comment]
https://github.com/mmvanheusden/SteamDepotDownloaderGUI/releases/tag/v2.4.1-deck

I don't plan on integrating it into the main branch currently, because the codebase is  a mess right now. I'm planning to rewrite everything in Rust which will take some more months probably.
Let me know if it works!
