### ISSUE TITLE
idk why this happens

### ISSUE THREAD

**Issue by BBG56789** [mmvanheusden/SteamDepotDownloaderGUI#153]
Connecting to Steam3...Timeout connecting to Steam3.
Disconnected from Steam
Unable to get steam3 credentials.
Error: InitializeSteam failed

**Comment by mmvanheusden** [comment]
Steam blocked in your region? have you inputted your user+password?

**Comment by BBG56789** [comment]
yup my username and password were put in, it doesn't even show the steam guard thing. Also, im in the US, so it shouldn't be blocked???

**Comment by mmvanheusden** [comment]
> yup my username and password were put in, it doesn't even show the steam guard thing. Also, im in the US, so it shouldn't be blocked???


Do you happen to have any special characters in your username/password? also are you on the latest version?
