### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by erilakin** [mmvanheusden/SteamDepotDownloaderGUI#17]
Hey! So I've got a problem that whatever .NET I install it still says I don't have any .NET installed. Even when I try to download it throught the link in the error message.
Cheers,

**Comment by mmvanheusden** [comment]
Try uninstalling all your .net core instances, and then restarting your pc,
the restart part is important, because it refreshes your envoirement
variables

**Comment by erilakin** [comment]
I did uninstalled all of the .NET core instances and rebooted my OS. What's now? Should I install this recommended .NET or is there any other steps I should do?

**Comment by erilakin** [comment]
nvm figured out that i need to download x86 one :) thx for help overall
