### ISSUE TITLE
Passwords with two percentage sign gets cut off

### ISSUE THREAD

**Issue by sudo-Juergens** [mmvanheusden/SteamDepotDownloaderGUI#179]
Hello,

the password i provided for steam contains two % signs and everything between these is cut when executing the .bat.

e.g.   Password = 1234%567%89 turns into 123489

The problem seems to be that % is not escaped with another % sign. Manually changing above password in the script to 1234%%567%%89 fixes the issue

Platform: Windows 11
Version:  2.4.1

**Comment by mmvanheusden** [comment]
Hi, thanks alot for your useful bug report!
I will look into this when I get home from vacation. No time for coding here :)

The special characters aren't escaped properly as it seems. That problem sucks and I have to write a proper universal implementation for it. Thanks for your report!

**Comment by mmvanheusden** [comment]
![image](https://github.com/mmvanheusden/SteamDepotDownloaderGUI/assets/50550545/0d6ff335-65cc-43f7-9676-20fcaf9a757a)
That's odd
