### ISSUE TITLE
It should use dotnet 5.0

### ISSUE THREAD

**Issue by jeiea** [mmvanheusden/SteamDepotDownloaderGUI#18]
**Is your feature request related to a problem? Please describe.**
Non PC adept user doesn't know they should install .net 5.0 to use DepotDownloader. Someone couldn't derive the solution of 'dotnet' command failure.

**Describe the solution you'd like**
Migrate this tool to .net 5.0, it will alerts to install .net if not installed.

**Describe alternatives you've considered**
Detect .net installation and guide to install.

**Comment by mmvanheusden** [comment]
Hi. This is already included in the README.md

**Comment by jeiea** [comment]
I think readme is not sufficient but if you think this is not necessary improvement I won't continue this discussion.

**Comment by mmvanheusden** [comment]
so you want like that the program tries to detect if dotnet is installed
and if not, display a popup?

**Comment by jeiea** [comment]
I prefer the former, just using .net 5. Current behavior is if users miss the step 1, they will fail at the step 15. There is little possibility of looking back from the step 1. If they could think of this, they would have already been people who knew how to use the CLI tool.

**Comment by mmvanheusden** [comment]
Do you think it is possible to bundle dotnet with Depot downloader? that would completely solve this issue.

**Comment by jeiea** [comment]
It is possible but it will increase the bundle size to almost 50MB and it requires another hosting location. Maybe republishing depotdownloader with target runtime to portable, check produce single file in file publishing options is what you think.

**Comment by SlejmUr** [comment]
As I know, you cant publish a single file with portable option, only if you select OS specific.
Maybe if you edit the publishing xml you can, but i never tried.
And to best way to check dotnet is probably Reg check.
Or dig tru your C filesystem. And if someone installed on D it not works for him.
And you also need some dotnet to actually start this tool too

**Comment by jeiea** [comment]
I didn't think of multiplatform, but it seems to say the difficulty of bundling or detecting .net 5.
So why not just use .net 5? I could see an alert guiding me to the .net 5 installation link with .net 5 executable when I missed that.
Without .net 5, this is just unusable. I can't find the reason to stick to this.

**Comment by SlejmUr** [comment]
You can do that
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/
Have fun to migrate to Dotnet 5.0

**Comment by SlejmUr** [comment]
I tried today using that migration.
Net.Http and Systeam.IO.Compression is not show as possible can use.
Tried both VS 2019/2022 version , same result

**Comment by SlejmUr** [comment]
It's me again!
After some of the dotnet 6.0 can be used WinForm, and I actually worked for it in some way.
I should say to migrate to dotnet 6.0

Also FunFact:
If you actually install the font style you dont need to do
