### ISSUE TITLE
Disconnected from Steam

### ISSUE THREAD

**Issue by vipyzr** [mmvanheusden/SteamDepotDownloaderGUI#183]
C:\Users\ADMINI~1\AppData\Local\Temp\2g0BptNgUi2KaRcj0D3F9g9SRQR>dotnet "E:\steam\config\stUI\depotdownloader\DepotDownloader.dll"  -app 1876890 -depot 1876891 -manifest 3049407793261410549 -dir D:\dwon\yj\1876890 -max-servers 50 -max-downloads 16
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 24
Got AppInfo for 1876890
App 1876890 (Wandering Sword) is not available from this account.
Disconnected from Steam

C:\Users\ADMINI~1\AppData\Local\Temp\2g0BptNgUi2KaRcj0D3F9g9SRQR>

**Comment by mmvanheusden** [comment]
You can't download paid games without an account.
