### ISSUE TITLE
Dotnet not found

### ISSUE THREAD

**Issue by SolariaStarz** [mmvanheusden/SteamDepotDownloaderGUI#192]
Downloaded .NET, closed the Depot Downloader, still says .NET isn't found. I tried both the one linked in the launcher, and the 8.0 version, nothing has worked!

**Comment by mmvanheusden** [comment]
See #193. You need to install a .NET SDK

**Comment by 0x8008** [comment]
Tried the latest Windows release and even after installing the .NET SDK the program explicitly links me to and re-launching it it does not work as it still asks for dotnet.
