### ISSUE TITLE
I can't download some files of CS:GO!

### ISSUE THREAD

**Issue by dztoshiba43** [mmvanheusden/SteamDepotDownloaderGUI#209]
Hi, 
I want to download this [depot 730 732 4052860265997222525), it's CS:GO files
(https://steamdb.info/depot/732/manifests/)

This error appear: 
-------------------------------------------------
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 187
Got AppInfo for 730
Using app branch: 'public'.
Depot 732) is not available from this account.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam
-------------------------------------------------
what can I do?

![error1](https://github.com/user-attachments/assets/46cd20e2-052e-4887-b9ec-f76d2a5535fb)

**Comment by Flawake** [comment]
From mmvanheusden:
Valve, the company behind steam and CS:GO has locked down all of the old manifests of CS:GO
