### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by mmvanheusden** [mmvanheusden/SteamDepotDownloaderGUI#21]
@SlejmUr
Hi, I am planning on rewriting the software in a different toolbox, something that works on Linux.
I was thinking of using Electron or Swing Java for it.
I prefer a library with an easy syntax so it is probably going to be Electron.

Let me know what you think!

**Comment by SlejmUr** [comment]
Sure, have fun!
I am totally new in JS and Electron. So I might be only able to help with parsing the argument to launch the DD.
But It would be great to learn that too. 
Please say Electron is not Typescript :D

**Comment by mmvanheusden** [comment]
I got the software working under Linux using Wine, but I am still interested in a rewrite

**Comment by mmvanheusden** [comment]
Because developing C# desktop under Linux is not really possible/practical

**Comment by SlejmUr** [comment]
Yes, I understand that.

**Comment by mmvanheusden** [comment]
check the rewrite branch

**Comment by mmvanheusden** [comment]
does this look like a good ui framework with fancy buttons and stuff? https://elastic.github.io/eui/#/

**Comment by SlejmUr** [comment]
You asking the person who mostly dont care about UI stuff :D
But yes, looks good and fancy.  Also dont forget about swithcing modes.
For you/me need modes:
Dark, White , Amoled(?).
But it can be accept a mode "addon" css file. If you want

**Comment by mmvanheusden** [comment]
😂 will do. gotta go to bed now

**Comment by mmvanheusden** [comment]
@SlejmUr Like it? it's not done yet

![image](https://user-images.githubusercontent.com/50550545/175766470-09e2da49-c0db-4608-ba64-884ace030884.png)

**Comment by SlejmUr** [comment]
Yes, but it will be to go everything to center :P

**Comment by mmvanheusden** [comment]
Yes, soon:tm:

**Comment by SlejmUr** [comment]
check PR.
Also if you want you can add me on Discord.
SlejmUr#4007

**Comment by mmvanheusden** [comment]
I am really getting stuck with making the async file operations stable, if you know any javascript expert that might be able to help us, please contact him/her
