### ISSUE TITLE
SteamDepotDownloaderGUI download button doesn't do anything

### ISSUE THREAD

**Issue by yawamz** [mmvanheusden/SteamDepotDownloaderGUI#210]
SteamDepotDownloaderGUI-Windows-v2.4.2 download button doesn't do anything, except create the "depotdownloader-2.5.0.zip" folder everytime the button is pressed. Command prompt does not open, Steam was closed when using the downloader.

I installed the newest .NET 6.0 SDK, tried inputting different app, depot and manifest IDs for different versions of a game (Helldivers 2, version from 29.4.2024.), tried setting the download location to multiple different disks - SSD C: disk where Windows 10 Pro (latest build) and Steam are installed, HDD D: disk, and SSD E: disk where Helldivers 2 is installed, everytime it's the same situation.

![depotdownloader](https://github.com/user-attachments/assets/30e1c4f3-5aac-47e6-a6f6-fe1a6f532d3d)

**Comment by crasebot1234** [comment]
yeah same here when i click it it says i dont have dotnet but when i install it and reopen it still does it anybody know how to help?

**Comment by mmvanheusden** [comment]
This should be fixed in the next version. Aiming to release soon.
