### ISSUE TITLE
Issue (might not be for your side)

### ISSUE THREAD

**Issue by Breelandthecat** [mmvanheusden/SteamDepotDownloaderGUI#226]
For some reason, whenever i try to download a depot manifest, it doesnt work. It fails to connect to the steam servers and wont ever succeed to do so. If you can, please fix this, if not, then idk if its my side or what.
![Edited](https://github.com/user-attachments/assets/ac812141-5e9e-4017-8c8a-f6bb08a9cb37)

**Comment by Breelandthecat** [comment]
Edited the image (deleted the original from history) because it contained my windows username

**Comment by Tommie1236** [comment]
how many times have you tried? there was a bit of a issue with depotdownloader itself iirc. 
i had to run it somewhere between 30 and 50 times for it to connect successfully last week.

https://github.com/SteamRE/DepotDownloader/issues/546

**Comment by Hitseditor** [comment]
Depot downloader recent update:
Updated SteamKit(allows using websocket servers to fix connections) to fix CDN auth tokens not working after Steam change.

**Comment by borobabe** [comment]
I'm having the same problem with the game "luck be a landlord".  I'm trying to create a modded version for use on a Trimui Smart Pro.  I get the same connection error as the OP.  I've added the game ID, depot ID and manifest number, then checked and rechecked the numbers.  I've tried several times to do this, but the error persists.

**Comment by mmvanheusden** [comment]
@Hitseditor @borobabe @Tommie1236 @Breelandthecat 

Fixed in https://github.com/mmvanheusden/SteamDepotDownloaderGUI/releases/tag/v2.4.3 . Please let me know if this solved the issue!

**Comment by borobabe** [comment]
Thank you, this has worked.  I had to install the net 8 framework, but the Depot Downloader provided the http link to copy and paste this.  The game graphics needed adjusting for the console, but the game is now working fine.  Thank you so much.

**Comment by Breelandthecat** [comment]
I Ran it many times, even tried on my laptop. Probably like around 5 to 10 times. It used to work fine before.

**Comment by Breelandthecat** [comment]
It also keeps happening.

**Comment by Breelandthecat** [comment]
> Thank you, this has worked. I had to install the net 8 framework, but the Depot Downloader provided the http link to copy and paste this. The game graphics needed adjusting for the console, but the game is now working fine. Thank you so much.

Which dot net 8.0 version specifically?

**Comment by Breelandthecat** [comment]
I Tried it with the latest version again, and it seems to work, it wasnt earlier. weird, i will keep this up for a few days in case it happens again. I Installed .net 8.0.0 for console applications, but idk if this is the correct version or not.

**Comment by borobabe** [comment]
I think it was that one; the console version.  I just copied and pasted the link to the Web browser, and downloaded what came up from that search.

**Comment by mmvanheusden** [comment]
Well damn it that's why I despite .NET so much. So many variants they all look the same and only 1 of them works.. I'm glad DepotDownloader started distributing .EXEs so this problem will hopefully soon become one of the past.
