### ISSUE TITLE
Add code of Conduct

### ISSUE THREAD

**Issue by Jaspreet099** [mmvanheusden/SteamDepotDownloaderGUI#35]
**Describe the solution you'd like**
I will add code of conduct

**Comment by mmvanheusden** [comment]
oops

**Comment by mmvanheusden** [comment]
Yes, that is a good idea

**Comment by Jaspreet099** [comment]
@mmvanheusden and also add Hacktoberfest tag 😄

**Comment by mmvanheusden** [comment]
Make a pr then
