### ISSUE TITLE
Anonymous Login

### ISSUE THREAD

**Issue by lilciv** [mmvanheusden/SteamDepotDownloaderGUI#37]
**Is your feature request related to a problem? Please describe.**
Feature Request - Anonymous login for dedicated server downloads

**Describe the solution you'd like**
When downloading certain manifests, for example Rust Dedicated Server (App 258550), you are required to login anonymously, not with steam credentials. Maybe if you did not fill out the username and password fields, it could auto log you in anonymously, bypassing the -username and -password flags?

**Describe alternatives you've considered**
The only way I've been able to do this using Depot Downloader is via the CLI

**Comment by mmvanheusden** [comment]
Will be implemented
