### ISSUE TITLE
Make UI more intuitive

### ISSUE THREAD

**Issue by AsciiJakob** [mmvanheusden/SteamDepotDownloaderGUI#42]
The UI looks really cool, but I have some ideas on how to make the UX a little bit better. 
1. First of all, the tooltips for the input fields could be put into placeholders inside the input fields instead, as hovering over the input field is not that intuitive since it's hidden by default. Also, some of the tooltips were quite unnecessary as the information they displayed was already obvious from the input field label, hence they would only get in the way. I already played around with this, and I'm going to make a pull request soon.
2. Another thought I had was that there should be a `*` next to all the fields that are mandatory, since that is a very common practice.
3. And lastly, the `Please fill in all required fields.` message could be improved by maybe marking the input fields that are not filled in with red.
4. One thought that I had was to add a little question mark next to the `App ID`, `Depot ID`, and `Manifest ID` fields, that when hovered over would display help for how to get those values. But I realized that this isn't necessary, since someone would never download this program if they didn't know what those were. Do you agree?

What do you think? Any suggestions or ideas or disagreements?

**Comment by mmvanheusden** [comment]
I agree with all your points, are you also going to open a pull request for point `2` and `3`?

**Comment by AsciiJakob** [comment]
> I agree with all your points, are you also going to open a pull request for point `2` and `3`?
Yep, though I have yet to work on them. I'll start working on point 2 tomorrow

**Comment by AsciiJakob** [comment]
Unless there are any issues with the PR I just submitted, I'm quite happy with the changes I've done.
The only suboptimal thing left is that a scrollbar appears when the `Please fill in all required fields.` notice pops up. The only way that this could be prevented is if there is some blank open space that it could appear in without creating new space, or if there was a different way of showing it. Perhaps the message is not even necessary.
I don't know, I'll leave that to you if you feel as bothered as me by it, though it's not really that big of an issue it's just something very little. Getting annoyed by something so small, says a lot about the UX I suppose.
Thanks for letting me contribute to the project, and I wish you good luck with it! Feel free to close the issue once you merge and if everything is alright
