### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by mcbravey** [mmvanheusden/SteamDepotDownloaderGUI#82]
the foloowing happens when i tried downloading despotism3k and sifu. i tried with and without account and the results were the same

No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 215
Got AppInfo for 699920
App 699920 (Despotism 3k) is not available from this account.
Disconnected from Steam

**Comment by mmvanheusden** [comment]
Seems like you are trying to download a game that you don't own.
**You need to own a game in order to download it, unless it it free**

**Comment by mcbravey** [comment]
> Seems like you are trying to download a game that you don't own. **You need to own a game in order to download it, unless it it free**

oh my god im sorry i thought i could download any game
